src/com/shop/domain/Cart.java
package com.shop.domain;

import com.shop.Price;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Set;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"cartDetailSet", "user"})
public class Cart implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    Set<CartDetail> cartDetailSet;

    @OneToOne
    User user;

    @Transient
    Price price;

    public void addCartDetail(CartDetail cartDetail) {
        cartDetail.setCart(this);
        cartDetailSet.add(cartDetail);
    }

    public BigDecimal getTotalGrossPrice() {
        return cartDetailSet.stream().map(cd -> cd.getAmount().multiply(cd.getPrice().getGrossPrice()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    public BigDecimal getTotalNetPrice() {
        return cartDetailSet.stream().map(cd -> cd.getAmount().multiply(cd.getPrice().getNetPrice()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }
}

src/com/shop/domain/Order.java
package com.shop.domain;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Comparator;
import java.util.Set;

@Entity
@Table(name = "orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"orderDetailSet", "orderComplaintSet", "orderHistorySet"})
public class Order implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    BigDecimal totalNet;
    BigDecimal totalGross;

    @ManyToOne
    @JoinColumn
    User user;

    //owner of relation is order detail
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    Set<OrderDetail> orderDetailSet;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    Set<OrderHistory> orderHistorySet;

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinTable(
            // joinColumn(order_complaint_id - column name in new table, id - key to joining table)
            // + column name in entity with joining key
            joinColumns = @JoinColumn(name = "order_complaint_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "order_id")
    )
    Set<OrderComplaint> orderComplaintSet;

    public Order(BigDecimal totalGross, User user) {
        this.totalGross = totalGross;
        this.user = user;
    }

    public void addOrderDetail(OrderDetail orderDetail) {
        orderDetail.setOrder(this);
        orderDetailSet.add(orderDetail);
    }

    public void addOrderHistory(OrderHistory orderHistory) {
        orderHistory.setOrder(this);
        this.orderHistorySet.add(orderHistory);
    }

    public OrderHistory getCurrentOrderHistory() {
        return this.getOrderHistorySet().stream().min(Comparator.comparing(OrderHistory::getId))
                .orElse(new OrderHistory());
    }
}

src/com/shop/domain/OrderHistory.java
package com.shop.domain;

import com.shop.OrderStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderHistory implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    LocalDateTime statusDate;

    @Enumerated(EnumType.STRING)
    OrderStatus orderStatus;

    @ManyToOne
    @JoinColumn
    Order order;
}

src/com/shop/domain/Product.java
package com.shop.domain;

import com.shop.Price;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDate;
import java.util.Set;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"orderDetailSet", "cartDetailSet", "productRatingSet"})
public class Product implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    String name;

    @ManyToOne
    @JoinColumn
    Category category;

    @Column()
    LocalDate date;

    @Embedded
    Price price;

    String description;

    @Lob
    byte[] image;

    @OneToMany(mappedBy = "product")
    Set<OrderDetail> orderDetailSet;

    @OneToMany(mappedBy = "product")
    Set<CartDetail> cartDetailSet;

    @OneToMany(mappedBy = "product")
    Set<ProductRating> productRatingSet;
}

src/com/shop/servlets/LoginServlet.java
package com.shop.servlets;

import com.shop.domain.User;
import com.shop.repository.UserRepository;

import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Optional;

public class LoginServlet extends HttpServlet {
    //  HttpServletRequest contains data from the client (browsers)
    //  e.g. parameters, data from the form, cookies,
    //  HttpServletResponse contains data that will be sent to the client (browsers)
    //  e.g. send HTML code, cookies, redirect
    @Override
    public void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String password = req.getParameter("password");
        String email = req.getParameter("email");

        System.out.println("password: " + password + " email: " + email);

        Optional<User> byEmailAndPassword = UserRepository.findByEmailAndPassword(email, password);

        byEmailAndPassword.ifPresent(x -> System.out.println("User id: " + x.getId()));

        if (byEmailAndPassword.isPresent()) {
            resp.addCookie(new Cookie("email", byEmailAndPassword.get().getEmail()));
        }
        req.getRequestDispatcher("/index.jsp").forward(req, resp);
    }
}

src/com/shop/servlets/RegisterServlet.java
package com.shop.servlets;

import com.shop.domain.User;
import com.shop.repository.IRepository;
import com.shop.repository.UserRepository;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Optional;

public class RegisterServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String firstName = req.getParameter("firstName");
        String lastName = req.getParameter("lastName");
        String email = req.getParameter("email");
        String password = req.getParameter("password");
        String password2 = req.getParameter("password2");

        boolean isValid = true;
        if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty() || password2.isEmpty()) {
            System.out.println("Complete the form with your information!");
            isValid = false;
        }

        if (!password.equals(password2)) {
            System.out.println("Passwords are not the same!");
            isValid = false;
        }

        Optional<User> byEmail = UserRepository.findByEmail(email);
        if (byEmail.isPresent()) {
            isValid = false;
            System.out.println("User with this email already exists!");
        }

        if (isValid) {
            User user = new User();
            user.setEmail(email);
            user.setPassword(password);
            user.setFirstName(firstName);
            user.setLastName(lastName);
            IRepository.save(user);
        }
        req.getRequestDispatcher("/index.jsp").forward(req, resp);
    }
}

WebContent/cart.jsp
<%@ page import="com.shop.repository.CartRepository" %>
<%@ page import="com.shop.domain.Cart" %>
<%@ page import="java.util.Optional" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jeff Shop - cart</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <%@include file="head.jsp"%>

    <%
        if (userFromCookie != null) {
            Optional<Cart> byUserId = CartRepository.findByUserId(userFromCookie.getId());
            if (byUserId.isPresent()) {
                pageContext.setAttribute("cart",byUserId.get());
            }
        }
    %>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <%@include file="leftMenu.jsp"%>
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">
                <h2>Cart</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Product name</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Net price</th>
                            <th scope="col">Gross price</th>
                            <th scope="col">Total net</th>
                            <th scope="col">Total gross</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${cart.cartDetailSet}" var="cd" varStatus="it">
                        <tr>
                            <th scope="row">${cd.product.name}</th>
                            <td><fmt:formatNumber type="number" minFractionDigits="0" maxFractionDigits="0"
                                                  value="${cd.amount}"/>
                                <a href="/decreaseProductAmount?productId=${cd.product.id}&method=add">
                                    <i class="fas fa-plus-square"></i></a>
                                <a href="/decreaseProductAmount?productId=${cd.product.id}&method=subtract">
                                    <i class="fas fa-minus-square"></i></a>
                                </td>
                            <td><fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                  value="${cd.price.netPrice}"/></td>
                            <td><fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                  value="${cd.price.grossPrice}"/></td>
                            <fmt:formatNumber var="totalNetPrice" type="number" minFractionDigits="2" maxFractionDigits="2" value="${cd.price.netPrice.multiply(cd.amount)}"/>
                            <fmt:formatNumber var="totalGrossPrice" type="number" minFractionDigits="2" maxFractionDigits="2" value="${cd.price.grossPrice.multiply(cd.amount)}"/>
                            <td>${totalNetPrice}</td>
                            <td>${totalGrossPrice}</td>
                            <td></td>
                        </tr>
                    </c:forEach>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td colspan="3"><b>Total:</b></td>
                            <td><fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                  value="${cart.totalNetPrice}"/></td>
                            <td><fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                  value="${cart.totalGrossPrice}"/></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
                <!-- /.card -->

                <div class="row">
                    <div class="col-md-6">
                        <h5>Delivery method:</h5>
                        <label>
                            <select class="form-control">
                                <option>Courier</option>
                                <option>In-store pickup</option>
                            </select>
                        </label>
                    </div>
                    <div class="col-md-6">
                        <h5>Delivery address</h5>
                        <div class="col-md-12">
                            <label>City</label>
                            <input type="text" class="form-control" name="city"/>
                        </div>
                        <div class="col-md-12">
                            <label>Zip code</label>
                            <input type="text" class="form-control" name="zipCode"/>
                        </div>
                        <div class="col-md-12">
                            <label>Street</label>
                            <input type="text" class="form-control" name="street"/>
                        </div>
                    </div>
                </div>

                <div>
                    <a href="/createOrder" class="btn btn-success">Buy and pay</a>
                </div>

            </div>
            <!-- /.col-lg-9 -->

        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <%@include file="footer.jsp"%>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

WebContent/complaint.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <%@include file="head.jsp"%>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <%@include file="leftMenu.jsp"%>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div class="card-body">
                    <h3 class="card-title">Zamówienie numer 333</h3>
                    <h4>kwota 333zl</h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>

                </div>

                <div class="row">
                    <h3>Zgłoś reklamację</h3>

                    <div class="col-md-12">
                        <textarea class="form-control" id="description" rows="3"></textarea>
                    </div>
                    <div class="col-md-12">
                        <button class="btn btn-warning">Zgłoś reklamację</button>
                    </div>
                </div>



            </div>
            <!-- /.col-lg-9 -->

        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <%@include file="footer.jsp"%>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

WebContent/footer.jsp
<%--
  Created by IntelliJ IDEA.
  User: piotr
  Date: 14.04.2018
  Time: 13:41
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Jeff Shop 2018</p>
    </div>
    <!-- /.container -->
</footer>

WebContent/head.jsp
<%@ page import="com.shop.UserSessionHelper" %>
<%@ page import="com.shop.domain.User" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: piotr
  Date: 14.04.2018
  Time: 13:22
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    User userFromCookie = UserSessionHelper.getUserFromCookie(request.getCookies());
    if (userFromCookie != null) {
        pageContext.setAttribute("user", userFromCookie);
    }
%>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/index.jsp">Jeff Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <c:if test="${user == null}">
                    <li class="nav-item">
                        <a class="nav-link" href="/login.jsp">Login</a>
                    </li>
                </c:if>
                <c:if test="${user != null}">
                    <li class="nav-item">
                        <a class="nav-link" href="/cart.jsp">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/orderHistory.jsp">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">${user.firstName} ${user.lastName}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                </c:if>
            </ul>
        </div>
    </div>
</nav>

WebContent/index.jsp
<%@ page import="com.shop.repository.ProductRepository" %>
<%@ page import="com.shop.domain.Product" %>
<%@ page import="java.util.List" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>
<%
    List<Product> allProduct = ProductRepository.findAll();
    pageContext.setAttribute("allProduct", allProduct);

    if (request.getParameter("isSuccessLogout") != null && request.getParameter("isSuccessLogout").equals("true")) {
        pageContext.setAttribute("info", "You are logged out!");
    }
%>
<body>

<!-- Navigation -->
<%@include file="head.jsp" %>

<c:if test="${info != null && info.length() > 0}">
    <div class="alert alert-danger" role="alert">${info}</div>
</c:if>
<!-- Page Content -->
<div class="container">

    <div class="row">

        <%@include file="leftMenu.jsp" %>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                <c:forEach items="${allProduct}" var="product">

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="/product.jsp?productId=${product.id}">
                                <img class="card-img-top" src="/productImage?productId=${product.id}" alt=""></a>
                            <!--700x400-->
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="/product.jsp?productId=${product.id}">${product.name}</a>
                                </h4>
                                <h5>${product.price.grossPrice} zł</h5>
                                <h6>${product.price.netPrice} zł</h6>
                                <p class="card-text">${product.description}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                            </div>
                        </div>
                    </div>

                </c:forEach>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<%@include file="footer.jsp" %>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

WebContent/leftMenu.jsp
<%--
  Created by IntelliJ IDEA.
  User: piotr
  Date: 14.04.2018
  Time: 13:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="col-lg-3">

    <h1 class="my-4">Categories</h1>
    <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
    </div>

</div>

WebContent/login.jsp
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login - Jeff Shop</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>

<body>
    <div class="container">
        <div class="row" id="pwd-container">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <section class="login-form">
                    <form method="post" action="/login" role="login">
                        <div>
                            <a class="navbar-brand" href="/index.jsp">Jeff Shop</a>
                        </div>
                        <%--<img src="http://i.imgur.com/RcmcLv4.png" class="img-responsive" alt="" />--%>
                        <input type="email" name="email" placeholder="Email" required class="form-control input-lg" value="mail@gmail.com" />

                        <input type="password" name="password" class="form-control input-lg" id="password" placeholder="password" aria-required="true" required="" />

                        <%--<div class="pwstrength_viewport_progress"></div>--%>
                        <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Sign in</button>
                        <div>
                            <a href="/register.jsp">Create account</a>
                        </div>
                    </form>
                    <div class="form-links">
                        <a href="#">www.website.com</a>
                    </div>
                </section>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</body>
</html>

WebContent/orderHistory.jsp
<%@ page import="com.shop.domain.Order" %>
<%@ page import="com.shop.repository.OrderRepository" %>
<%@ page import="java.util.List" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <%@include file="head.jsp"%>

    <%
        if (userFromCookie != null) {
            List<Order> allOrders = OrderRepository.findAllByUserId(userFromCookie.getId(),0);
            pageContext.setAttribute("userOrders", allOrders);
        }
    %>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <%@include file="leftMenu.jsp"%>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Net price</th>
                            <th scope="col">Gross price</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>

                    <c:forEach items="${userOrders}" var="order" varStatus="lp">
                        <tr>
                            <th scope="row">${lp.index+1}</th>
                            <td>${order.currentOrderHistory.statusDate}</td>
                            <td>${order.currentOrderHistory.orderStatus}</td>
                            <td>${order.totalNet}</td>
                            <td>${order.totalGross}</td>
                            <td><a href="/order.jsp?orderId=${order.id}">Details</a></td>
                        </tr>
                    </c:forEach>

                    </tbody>
                </table>
                <!-- /.card -->


            </div>
            <!-- /.col-lg-9 -->

        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <%@include file="footer.jsp"%>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

WebContent/page.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <%@include file="head.jsp"%>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <%@include file="leftMenu.jsp"%>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div class="card-body">
                    <h3 class="card-title">Zamówienie numer 333</h3>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>

                </div>




            </div>
            <!-- /.col-lg-9 -->

        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <%@include file="footer.jsp"%>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>